### ISSUE TITLE
Anti-ad filter fails on capitalization

### ISSUE THREAD

**Issue by hyzchip** [12joan/twitter-client#19]
First off, thank you so much for this great tool!  This is a perfect replacement for Nitter, and I will probably keep using it even if Nitter itself gets fixed.

Anyway, the bug itself.  I noticed this following the upgrade after #17 was merged.  It works great at filtering out ads; that's not the issue.  Twitter usernames are not case sensitive; an alternate capitalization would still redirect to the same account.  However, with this tool, tweets get rejected if the screen_name and username are identical except for capitalization, filtering out legitimate tweets.

For example:
localhost:3000/cbcmurdoch/rss is blank.
localhost:3000/CBCMurdoch/rss works.
localhost:3000/dailyblazedose/rss is blank.
localhost:3000/DailyBlazeDose/rss works.

This is really a minor issue; I simply had to update a few RSS feeds to match the correct screen_name, and everything works fine again.

Thanks for all the hard work!

**Comment by us3r1d** [comment]
I can look to see if there's a case-insensitive compare in JS to replace the `===` in that check.

**Comment by us3r1d** [comment]
The Internet seems to think that `string.[toUpperCase()` is the way to do that in JS.

I've tested it on my server and it's working as expected, so I'll make a PR.

**Comment by us3r1d** [comment]
PR: https://github.com/12joan/twitter-client/pull/21

Thanks for catching that, hyzchip.

**Comment by us3r1d** [comment]
Hah; turns out this was affecting my server too and I hadn't noticed it.  I was pulling "@EFF", but their actual screen_name is "@eff"; just got a wad of tweets processed.  So, extra thanks.  :-)
