### ISSUE TITLE
Add additional client credentials

### ISSUE THREAD

**Issue by 12joan** [12joan/twitter-client#2]
Currently only using one set of credentials

**Comment by nickchen120235** [comment]
I can work on this. Should I also include an identifier for each credential for #3?

**Comment by 12joan** [comment]
@nickchen120235 Thanks! Yes, adding an ID would be a good idea.

**Comment by 12joan** [comment]
I would pick a set of credentials randomly for now, unless you're planning to work on #3 at the same time. 🙂

**Comment by nickchen120235** [comment]
Yep I'm thinking `Math.floor(Math.random() * arr.length)` for now.

**Comment by nickchen120235** [comment]
So after some experiments, only the iPad key pair works for now.
