### ISSUE TITLE
needs regular restarting?

### ISSUE THREAD

**Issue by us3r1d** [12joan/twitter-client#35]
I don't know node well, so I don't have any theories for why this happens, but my install only seems to run well for 2-3 days before it just stops serving new tweets.  I'll try to do more looking into it the next time it happens (which will be a few days, since I just re-started it again :-)

That box is mirroring ~80 Twitter accounts, for ~400 tweets-per-day.

**Comment by 12joan** [comment]
That's strange. My Docker install has been up for 4 days currently without incident for a similar volume of traffic. Next time it happens for you, try sending a test request using curl; it would be interesting to see whether it produces an error in the application logs or just times out.

**Comment by 12joan** [comment]
Has the problem happened again over the past week? If not, I think we can safely close this issue.

**Comment by us3r1d** [comment]
No, it hasn't  (&(&^$*^%#&%

Isn't that just always the way, when you talk to someone about a tech problem that seems consistent it just stops?  :-)

I'm going to keep watching it, and if I can come up with a consistent description I'll bring it up again.  Thanks.

**Comment by us3r1d** [comment]
service is running, but last logged activity is from yesterday

curl _does_ return a result

re-starting the stork process resulted in tweets coming in, though, so the issue is likely with stork and not here after all  :-)
