### ISSUE TITLE
Add instructions for deployment

### ISSUE THREAD

**Issue by 12joan** [12joan/twitter-client#5]
Anyone familiar with Docker should be able to figure it out, but it would be good to help out users who aren't so familiar with it.

Note that `command: 'yarn dev'` should be used in development but not production.

**Comment by aki-k** [comment]
Here's how I did it in Fedora 37:
```
sudo -i
dnf install yarnpkg
dnf -y install dnf-plugins-core
dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
usermod -a -G docker ${USER}
exit
```
Logout & login
```
sudo systemctl enable --now docker
mkdir -p ${HOME}/docker
cd ${HOME}/docker
git clone https://github.com/12joan/twitter-client.git
cd twitter-client
yarn install
docker compose up --build
```
Access the web UI at http://0.0.0.0:3000/

I have no idea how to read the data in another mode than the Firefox JSON view, though :)
