### ISSUE TITLE
The short usage guide says to use /:username but /username worked for me instead

### ISSUE THREAD

**Issue by aki-k** [12joan/twitter-client#7]
Example:

not working: http://0.0.0.0:3000/:petterij

working: http://0.0.0.0:3000/petterij

**Comment by 12joan** [comment]
Hi, sorry for the confusion.

Putting a colon before a URL component is a standard syntax for indicating that the URL component is a variable and should be substituted. Feel free to add a note to the README clarifying this if you feel it would be useful.
